name: Java 17

on:
  push:
    branches: [stable, development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Checkout timefold-solver
        uses: actions/checkout@v3
        with:
          path: 'timefold-solver'
          repository: 'TimefoldAI/timefold-solver'

      - name: Build timefold-solver
        run: |
          cd timefold-solver
          mvn -B -Dfull verify
          cd ..

      - name: Checkout timefold-quickstarts
        uses: actions/checkout@v3
        with:
          path: 'timefold-quickstarts'

      - name: Build timefold-quickstarts
        run: |
          cd timefold-quickstarts
          mvn -B -Dfull verify
          cd ..
