name: Java 17 Linux

on:
  push:
    branches: [stable, development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO Run multiple OS.
#    runs-on: ${{matrix.os}}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout timefold-solver
        uses: actions/checkout@v3
        with:
          path: 'timefold-solver'
          repository: 'TimefoldAI/timefold-solver'

      - name: Checkout timefold-quickstarts
        uses: actions/checkout@v3
        with:
          path: 'timefold-quickstarts'

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build timefold-solver
        run: |
          cd timefold-solver
          mvn -B -Dfull install -DskipTests
          cd ..

      - name: Build timefold-quickstarts
        run: |
          cd timefold-quickstarts
          mvn -B -Dfull verify
          cd ..
